version: '3'
services:

  postgres:
    image: 'postgres:9.6-alpine'
    volumes:
      - postgres-contadigital-volume:/var/lib/postgresql/data
    container_name: "postgres"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contadigital

  pgadmin4:
    image: 'dpage/pgadmin4:5.5'
    volumes:
      - pgadmin-contadigital-volume:/var/lib/pgadmin
    container_name: "pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 8082:80

volumes:
  postgres-contadigital-volume:
  pgadmin-contadigital-volume: